import { Metadata } from "next";
import AboutPage from "./aboutPage";

export const metadata: Metadata = {
  title: "Bingers - About",
  description: "Generated by create next app",
};

const About = () => {
  return <AboutPage />;
};

export default About;
