import { Metadata } from "next";
import ContactPage from "./contactPage";

export const metadata: Metadata = {
  title: "Bingers - Contact",
  description: "Generated by create next app",
};

const Contact = () => {
  return <ContactPage />;
};

export default Contact;
