import { Metadata } from "next";
import SkillsPage from "./skillsPage";

export const metadata: Metadata = {
  title: "Bingers - Skills",
  description: "Generated by create next app",
};

const Skills = () => {
  return <SkillsPage />;
};

export default Skills;
