import { Metadata } from "next";
import HomePage from "@/app/homePage";

export const metadata: Metadata = {
  title: "Bingers - Home",
  description: "Generated by create next app",
};

export default function Home() {
  return <HomePage />;
}
